version: '3'

services:
  nginx:
    container_name: restnginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:80"
    volumes:
        - type: bind
          source: /usr/share/nginx/html/rest/restf
          target: /restf:ro
